import { Search, GitCompare, FileSignature, CheckCircle2, CreditCard, Bell, Map, Users2 } from 'lucide-react';
import { PublicShell, PublicHero, CTASection } from '@/components/public/public-chrome';

export const metadata = { title: 'How It Works — Umrah Connect' };

const STEPS = [
  { Icon: Search, t: 'Search', d: 'Browse published hotel, transport, visa and package listings. Check the provider information on each service.' },
  { Icon: GitCompare, t: 'Compare', d: 'Review price, location, inclusions and available review information on each listing. Confirm availability with the provider.' },
  { Icon: FileSignature, t: 'Request / Book', d: 'Send a request or book directly. Operators receive your enquiry and respond with quotations and offers.' },
  { Icon: CheckCircle2, t: 'Review Confirmation', d: 'Review the service, dates, party size and supported price estimate. Nightly and custom rates require a provider inquiry.' },
  { Icon: CreditCard, t: 'Payment / Invoice', d: 'Use the payment options enabled for your invoice. Recorded payments, outstanding balances and booking status are separate.' },
  { Icon: Bell, t: 'Notifications', d: 'Read the notifications generated by supported platform actions in your account.' },
  { Icon: Map, t: 'Travel Management', d: 'View your marketplace bookings and requests. Ask your operator for group itineraries and personal visa updates.' },
  { Icon: Users2, t: 'Provider Coordination', d: 'Provider workspaces organize their respective booking, inventory, assignment and application records.' },
];

export default function WorkflowPage() {
  return (
    <PublicShell>
      <PublicHero
        eyebrow="HOW UMRAH CONNECT WORKS"
        title="Simple. Smart. Seamless."
        subtitle="Explore the supported service paths. Inquiry, request, booking and payment actions vary by service and workspace."
      />
      <section className="max-w-6xl mx-auto px-6 lg:px-8 pb-16">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {STEPS.map(({ Icon, t, d }, i) => (
            <div key={t} className="bg-white rounded-2xl border border-sandstone/60 p-5">
              <div className="flex items-center justify-between mb-3">
                <div className="w-11 h-11 rounded-xl bg-brand-50 flex items-center justify-center">
                  <Icon className="h-5 w-5 text-brand-600" />
                </div>
                <span className="text-[11px] font-bold text-gold-800">STEP {i + 1}</span>
              </div>
              <p className="font-heading font-bold text-gray-900">{t}</p>
              <p className="text-[13px] text-gray-600 mt-1.5 leading-relaxed">{d}</p>
            </div>
          ))}
        </div>
      </section>
      <CTASection title="See the full workflow inside the platform" subtitle="Explore services, discuss requirements and use the supported booking and account tools." />
    </PublicShell>
  );
}
