FROM uc-a11-orca-lab:local
USER root
# Audio plugins so speech-dispatcher can "play" into a null ALSA sink (no sound card in the lab).
RUN apt-get update && apt-get install -y --no-install-recommends speech-dispatcher-audio-plugins libasound2 alsa-utils \
    && rm -rf /var/lib/apt/lists/*
USER tester
RUN printf 'pcm.!default { type null }\nctl.!default { type hw card 0 }\n' > /home/tester/.asoundrc \
 && mkdir -p /home/tester/.config/speech-dispatcher \
 && cp /etc/speech-dispatcher/speechd.conf /home/tester/.config/speech-dispatcher/speechd.conf \
 && printf '\nAudioOutputMethod "alsa"\nDefaultModule espeak-ng\n' >> /home/tester/.config/speech-dispatcher/speechd.conf
