'use client';
import { Button, QueryFailure, LoadingState, Card, PageHeader } from '@/components/ui/system';
import { RefreshCw } from 'lucide-react';
import { useAdminSettings } from '@/hooks/use-admin';
export function AdminSettingsView(){
 const {data:s,isLoading,error,refetch}=useAdminSettings();
 if(error)return <QueryFailure error={error} onRetry={()=>void refetch()} />;
 const enforced=s?.enforced;
 return <div className="max-w-4xl space-y-5 pb-10"><PageHeader title="Platform settings" description="Current enforced configuration and recorded service categories." action={<Button variant="secondary" aria-label="Refresh platform settings" busy={isLoading} onClick={()=>void refetch()}><RefreshCw className="h-4 w-4" />Refresh</Button>} />{isLoading?<LoadingState label="Loading platform settings…" />:!s?<p role="status">Platform settings are unavailable.</p>:<><Card><h2 className="text-base font-semibold">Runtime configuration</h2><p className="mt-2 text-sm text-gray-600">These settings are read-only. Configuration changes require the platform operations team.</p><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[['KYC before activation',enforced?.kycRequiredBeforeActivation==null?null:enforced.kycRequiredBeforeActivation?'Required':'Not required'],['Payment provider',enforced?.paymentProvider],['Document storage',enforced?.storageDriver],['Mail delivery',enforced?.mailDriver],['Google sign-in',enforced?.googleSignIn==null?null:enforced.googleSignIn?'Enabled':'Disabled']].map(([label,value])=><div key={label}><dt className="text-xs font-medium text-gray-600">{label}</dt><dd className="mt-1 break-words text-sm">{value??'Not provided'}</dd></div>)}</dl><h3 className="mt-5 text-sm font-semibold">Organization types requiring KYC</h3><p className="mt-2 text-sm text-gray-600">{enforced?.organizationTypesRequiringKyc?.map((t:string)=>t.replace(/_/g,' ')).join(', ')||'Not provided'}</p></Card><Card><h2 className="text-base font-semibold">Marketplace categories</h2>{s.marketplaceCategories?.length?<ul className="mt-4 space-y-2">{s.marketplaceCategories.map((item:any)=><li key={item.category} className="flex justify-between gap-4 text-sm"><span>{item.category.replace(/_/g,' ')}</span><span>{item.count}</span></li>)}</ul>:<p className="mt-3 text-sm text-gray-600">No listings recorded.</p>}</Card><Card><h2 className="text-base font-semibold">Regulatory systems recorded</h2><p className="mt-2 text-sm text-gray-600">Application registry labels do not confirm a live registry connection.</p>{s.regulatorySystems?.length?<ul className="mt-4 space-y-2">{s.regulatorySystems.map((item:any)=><li key={item.system} className="flex justify-between gap-4 text-sm"><span>{item.system}</span><span>{item.count}</span></li>)}</ul>:<p className="mt-3 text-sm text-gray-600">No registry labels recorded.</p>}</Card></>}</div>;
}
