'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { apiClient } from '@/lib/api';
import { acceptSession } from '@/lib/session';
import { useAuthContext } from '@/components/providers/auth-provider';
import { PageHeader, Card, Alert, Button, Input, Select, FileUpload, QueryFailure } from '@/components/ui/system';
import { DocumentLink } from '@/components/ui/document-link';
export default function OnboardingPage() {
 const {user,setUser}=useAuthContext();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [documents,setDocuments]=useState<any[]>([]);const [form,setForm]=useState({type:'OPERATOR',name:'',country:'SA',licenseNumber:''});
 const traveler=user?.tenantSlug==='umrah-connect-travelers';const provider=!traveler;const canReadKyc=!!user?.permissions?.includes('core:tenant:read');
 const history=useQuery({queryKey:['organization','kyc'],enabled:canReadKyc,queryFn:async()=>(await apiClient.get('/tenants/me/kyc')).data.data as any[]});
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await apiClient.post('/onboarding/organization',form);const next=await acceptSession(data.data.tokens.accessToken);setUser(next);setMessage('Organization created. Submit verification documents for review.');}catch(e:any){setError(e?.response?.data?.error?.message||'Your organization could not be created.');}finally{setBusy(false);}};
 const upload=async(file?:File)=>{if(!file)return;setError('');if(file.size>15*1024*1024){setError('Choose a file no larger than 15 MB.');return;}setBusy(true);try{const body=new FormData();body.append('file',file);const {data}=await apiClient.post('/documents/kyc',body,{headers:{'Content-Type':'multipart/form-data'}});setDocuments(previous=>[...previous,data.data]);}catch(e:any){setError(e?.response?.data?.error?.message||'The document could not be uploaded.');}finally{setBusy(false);}};
 const submit=async()=>{setBusy(true);setError('');try{await apiClient.post('/tenants/me/kyc',{registrySource:'MANUAL',licenseNumber:form.licenseNumber||undefined,documents});setDocuments([]);setMessage('Verification documents submitted for review.');await history.refetch();}catch(e:any){setError(e?.response?.data?.error?.message||'Verification could not be submitted.');}finally{setBusy(false);}};
 return <div className="max-w-3xl space-y-6"><PageHeader title="Organization onboarding" description="Create a provider workspace and submit organization verification." />{user?.emailVerified===false&&<Alert title="Verify your email first">Confirm your account email before creating an organization. <Link href="/settings" className="underline">Account settings</Link></Alert>}{error&&<Alert title="Unable to continue">{error}</Alert>}{message&&<Alert tone="info" title="Organization update">{message}</Alert>}
 {!provider ? <Card><h2 className="text-lg font-semibold">Create your organization</h2><p className="mt-2 text-sm text-gray-600">A new organization starts pending verification. Creating it replaces your current workspace session.</p><form method="post" onSubmit={create} className="mt-5 space-y-4"><label className="block space-y-2 text-sm font-medium">Workspace type<Select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{[['OPERATOR','Operator / Agency'],['MU_ASSASA','Ground services'],['VENDOR_HOTEL','Hotel'],['VENDOR_TRANSPORT','Transport'],['VENDOR_VISA','Visa agency']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label className="block space-y-2 text-sm font-medium">Organization name<Input required minLength={2} maxLength={255} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} /></label><label className="block space-y-2 text-sm font-medium">Country code<Input required pattern="[A-Z]{2}" maxLength={2} value={form.country} onChange={e=>setForm({...form,country:e.target.value.toUpperCase()})} /></label><label className="block space-y-2 text-sm font-medium">License number (optional)<Input maxLength={100} value={form.licenseNumber} onChange={e=>setForm({...form,licenseNumber:e.target.value})} /></label><Button type="submit" busy={busy} disabled={!user?.emailVerified}>Create organization</Button></form></Card> : <Card><h2 className="text-lg font-semibold">Organization verification</h2><p className="mt-2 text-sm text-gray-600">Current workspace: {user?.tenantName}. Status: {user?.tenantStatus || 'Not provided'}. Verification requires authentic organization documents.</p>{user?.permissions?.includes('core:tenant:update')&&<div className="mt-5 space-y-4"><FileUpload label="Verification document (PDF or image, up to 15 MB)" accept=".pdf,.jpg,.jpeg,.png,.webp,.heic,.tiff" disabled={busy} onChange={e=>void upload(e.target.files?.[0])} /><ul className="space-y-2">{documents.map((doc,i)=><li key={i} className="text-sm">{doc.name||doc.filename||`Uploaded document ${i+1}`}</li>)}</ul><Button busy={busy} disabled={!documents.length} onClick={submit}>Submit for review</Button></div>}</Card>}
 {canReadKyc&&<Card><h2 className="text-lg font-semibold">Verification history</h2>{history.error ? <QueryFailure error={history.error} onRetry={()=>void history.refetch()} /> : history.isLoading ? <p role="status" className="mt-3 text-sm">Loading verification history…</p> : !history.data?.length ? <p className="mt-3 text-sm text-gray-600">No verification submissions yet.</p> : <ul className="mt-4 space-y-4">{history.data.map((item:any)=><li key={item.id} className="border-t pt-3 text-sm"><p>{item.verifiedAt ? 'Verified' : item.rejectionReason ? 'Changes required' : 'Awaiting review'}</p>{item.rejectionReason&&<p className="mt-2 text-red-700">{item.rejectionReason}</p>}{item.documents?.map((doc:any,i:number)=><DocumentLink key={i} documentId={item.id} kycIndex={i} name={doc.name||`Verification document ${i+1}`} />)}</li>)}</ul>}</Card>}
 </div>;
}
