'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { apiClient } from '@/lib/api';
import { useAuthContext } from '@/components/providers/auth-provider';
import { usePaymentProviders, useCreatePaymentIntent, usePayment } from '@/hooks/use-payments';
import { Alert, Button, Input, QueryFailure, LoadingState } from '@/components/ui/system';
const CardPayment=dynamic(()=>import('./card-payment'),{ssr:false,loading:()=> <LoadingState label="Loading secure payment form…" />});
export function PaymentGatewayPanel({invoiceId,currency,outstandingCents,onChanged,invoiceStatus}:{invoiceId:string;currency:string;outstandingCents:number;onChanged:()=>void;invoiceStatus?:string}){
 const {user}=useAuthContext();const providers=usePaymentProviders();const create=useCreatePaymentIntent();const [amount,setAmount]=useState('');const [intent,setIntent]=useState<any>(null);const [paymentId,setPaymentId]=useState<string>();const [error,setError]=useState('');const payment=usePayment(paymentId);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('payment');if(id&&/^[a-f\d-]{36}$/i.test(id))setPaymentId(id);},[]);
 const active=providers.data?.providers.find(p=>p.name===providers.data.active);const usable=active?.name==='stripe'&&active.configured&&!!active.publishableKey;const canPay=!!user?.permissions?.includes('finance:payment:process');const issued=!!invoiceStatus&&!['DRAFT','VOID','CANCELLED','PAID'].includes(invoiceStatus);
 const start=async()=>{setError('');const value=Number(amount);if(!Number.isFinite(value)||value<=0||Math.round(value*100)>outstandingCents){setError('Enter a positive amount within the outstanding balance.');return;}try{const next=await create.mutateAsync({invoiceId,amount:value,currency});if(!next.clientSecret)throw new Error('The provider did not return a secure payment form.');setIntent(next);setPaymentId(next.id);}catch(e:any){setError(e?.response?.data?.error?.message||e.message||'Payment could not be started.');}};
 const check=async()=>{try{await apiClient.post(`/payments/intents/${paymentId}/confirm`,{});await payment.refetch();onChanged();}catch(e:any){setError(e?.response?.data?.error?.message||'Payment status could not be checked.');}};
 if(providers.error||payment.error)return <QueryFailure error={providers.error||payment.error} onRetry={()=>{void providers.refetch();void payment.refetch();}} />;
 return <section className="uc-card space-y-4"><h2 className="text-base font-semibold">Card payment</h2>{providers.isLoading ? <LoadingState label="Checking payment provider…" /> : !canPay ? <Alert tone="info" title="Payment permission required">Your account can view the invoice but cannot collect payments.</Alert> : !issued ? <Alert tone="info" title="Invoice cannot take payments">Issue the draft invoice before collecting payment. Paid, void and cancelled invoices cannot take payments.</Alert> : !usable ? <Alert tone="info" title="Card payments unavailable">A configured card payment provider is required. No payment has been submitted.</Alert> : <><p className="text-sm text-gray-600">Outstanding: {currency} {(outstandingCents/100).toLocaleString()}{active?.testMode?' · Test mode':''}</p>{!intent&&<><label className="block space-y-2 text-sm font-medium">Amount<Input type="number" min="0.01" step="0.01" max={outstandingCents/100} value={amount} onChange={e=>setAmount(e.target.value)} /></label><Button busy={create.isPending} disabled={outstandingCents<=0} onClick={start}>Continue to secure payment</Button></>}{intent&&<CardPayment publishableKey={active!.publishableKey!} clientSecret={intent.clientSecret} paymentId={intent.id} onReconciled={()=>{void payment.refetch();onChanged();}} />}</>}{error&&<Alert title="Payment requires attention">{error}</Alert>}{payment.data&&<div role="status" className="space-y-2 border-t pt-4"><p className="text-sm font-medium">Server payment status: {payment.data.status}</p><Button variant="secondary" onClick={check} busy={payment.isFetching}>Check payment status</Button></div>}</section>;
}
